# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-funding

github:
  - tmontana1044-sketch
patreon:
  - YOUR_PATREON_NAME
ko_fi:
  - YOUR_KOFI_NAME
open_collective:
  - YOUR_OPEN_COLLECTIVE_SLUG
buy_me_a_coffee:
  - YOUR_BMC_NAME
paypal:
  - YOUR_PAYPAL_ME_USERNAME
